### ISSUE TITLE
Need a Favicon

### ISSUE THREAD

**Issue by sudi050** [ACM-Amrita-Amritapuri/Anime-World#8]
a favicon is needed for the webpage. it will look good if a quite nice logo is visible on the top of the tab.

if anyone wants to get this assigned, please let us know.

**Comment by Ritish134** [comment]
Hi there, excited to contribute can you assign me :)

**Comment by Ritish134** [comment]
Is it fine: 
![naruto](https://github.com/ACM-Amrita-Amritapuri/Anime-World/assets/121374890/7aeff913-6c78-48fc-b523-ed6128512faf)
